if !isdirectory(expand('~/.vim/undo'))
  call mkdir(expand('~/.vim/undo'), 'p')
endif

" Ctr-] >< Ctr-t
let mapleader = " "
set clipboard=unnamedplus,unnamed
set cursorline
set encoding=utf-8
set hidden
set hlsearch
set ignorecase
set incsearch
set mouse=a
set nobackup
set noswapfile
set nowrap
set nowritebackup
set path+=**
set rnu nu
set signcolumn=yes
set smartcase
set smartindent
" set so=20
set splitbelow
set splitright
set undodir=~/.vim/undo "make this folder first
set undofile
set updatetime=300
set wildignore+=*.pyc
set wildmenu
set confirm
set showtabline=2

" :verbose imap <tab>
" :@a to run content in register a
" nnoremap <silent> <cr> :put _<cr>
inoremap jk <Esc>
nnoremap j gj
nnoremap k gk
" nnoremap n nzz
" nnoremap N Nzz
nnoremap ]w <C-w>w
nnoremap [w <C-w>W
tnoremap ]w <C-w>w
tnoremap [w <C-w>W
nnoremap Y y$
nnoremap U <C-r>
nnoremap ; :
vnoremap ; :
nnoremap : ;
nnoremap ' `
tnoremap <esc> <C-\><C-n>
nnoremap <leader>. @:
nnoremap <leader><leader> <c-^>

nnoremap <leader>/ :BLines<cr>
nnoremap <leader>fc :History:<Cr>
nnoremap <leader>fd :Buffers<Cr>
nnoremap <leader>ff :Files<Cr>
nnoremap <leader>fg :Rg<Cr>
nnoremap <leader>fl :Files %:h<Cr>
nnoremap <leader>fm :History<Cr>
nnoremap <leader>fn :edit ~/.vim/vimrc<cr>
nnoremap <leader>gf :GFiles<Cr>

" paste and then = to indent to end of paste ]
nnoremap p p=`]
nnoremap P :put! "0=`]<cr>

nnoremap <bs> ciw
nnoremap c "_c
nnoremap C "_C
nnoremap x "_x
nnoremap <leader>d "_d
vnoremap <leader>d "_d
nnoremap <leader>b :ls<CR>:b<Space>
nnoremap <up> <C-u>zz<CR>
nnoremap <down> <C-d>zz<CR>
xnoremap < <gv
xnoremap > >gv
nnoremap <right> gt
nnoremap <left> gT

" Clipboard
augroup Osc52Yank
  autocmd!
  autocmd TextYankPost * if len(v:event.regcontents[0]) > 1 || len(v:event.regcontents) > 1 | call system("printf $'\\e]52;c;%s\\a' \"$(cat | base64)\" >> /dev/tty", v:event.regcontents) | endif
augroup END

" Autosave CursorHold, auto clean whitespace
augroup Useful
  autocmd!
  autocmd FocusLost * wa
  autocmd BufWritePre * %s/\s\+$//e
augroup END


call plug#begin('~/.vim/plugged')

" Plug 'machakann/vim-swap'
Plug 'catppuccin/vim'
Plug 'haya14busa/vim-asterisk'
Plug 'inkarkat/vim-ReplaceWithRegister'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/vim-easy-align'
Plug 'kana/vim-textobj-entire'
Plug 'kana/vim-textobj-user'
Plug 'machakann/vim-highlightedyank'
Plug 'markonm/traces.vim'
Plug 'mbbill/undotree'
Plug 'michaeljsmith/vim-indent-object'
Plug 'mkitt/tabline.vim'
Plug 'nathanaelkane/vim-indent-guides'
" Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'ntpeters/vim-better-whitespace'
Plug 'preservim/nerdtree'
Plug 'rhysd/clever-f.vim'
Plug 'romainl/vim-cool'
Plug 'romainl/vim-qf'
Plug 'sheerun/vim-polyglot'
Plug 'svban/YankAssassin.vim'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-dadbod'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rsi'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-vinegar'
Plug 'wellle/targets.vim'
Plug 'yegappan/mru'

call plug#end()

" Nerdtree g:NERDTreeMapPreview = 'p'
nnoremap <leader>et :NERDTreeToggle<CR>

" Easy align
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)

" Dadbob
let g:prod = "sqlite:prod.db"
let g:tablineclosebutton=1

" Undotree
nnoremap <leader>u :UndotreeToggle<cr>
if !exists('g:undotree_DiffAutoOpen')
    let g:undotree_DiffAutoOpen = 0
endif

let g:qf_window_bottom = 0
let g:qf_auto_open_quickfix = 0

" Vim-asterisk
let g:asterisk#keeppos = 1
map *  <Plug>(asterisk-z*)
map #  <Plug>(asterisk-z#)
map g* <Plug>(asterisk-gz*)
map g# <Plug>(asterisk-gz#)

" Fzf ctrl-a ctrl-q to select all and build quickfix list
let g:fzf_vim = {}

function! s:build_quickfix_list(lines)
  call setqflist(map(copy(a:lines), '{ "filename": v:val }'))
  copen
  cc
endfunction

let g:fzf_action = {
  \ 'ctrl-q': function('s:build_quickfix_list'),
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }

let $FZF_DEFAULT_OPTS = '--bind ctrl-a:select-all,ctrl-j:down,ctrl-k:up,right:preview-page-down,left:preview-page-up'
let g:fzf_vim.preview_window = ['right,60%', 'ctrl-/']
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.8 } }

" Replace with register
nmap <Leader>r  <Plug>ReplaceWithRegisterOperator
nmap <Leader>rr <Plug>ReplaceWithRegisterLine
xmap <Leader>r  <Plug>ReplaceWithRegisterVisual

" Theme, highlight, smartf
set termguicolors
color catppuccin_mocha
let g:cool_total_matches = 1
let g:highlightedyank_highlight_duration = 300
let g:clever_f_smart_case = 1


" Coc settings
" let g:coc_global_extensions = ['coc-json', 'coc-yaml', '@yaegassy/coc-ansible', 'coc-sh', 'coc-pyright']
" g:coc_suggest_disable = 1
" let g:coc_start_at_startup = 0
" nnoremap <leader>a :set filetype=yaml.ansible<cr>
" let g:coc_disable_startup_warning = 1
" let g:coc_filetype_map = {'yaml.ansible': 'ansible'}
" call coc#config('suggest.triggerAfterInsertEnter', v:false)
" call coc#config('suggest.minTriggerInputLength', 4)

" inoremap <silent><expr> <c-space> coc#refresh()
" inoremap <silent><expr> <tab> coc#pum#visible() ? coc#pum#confirm()
"                               \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

" function! CheckBackspace() abort
"   let col = col('.') - 1
"   return !col || getline('.')[col - 1]  =~# '\s'
" endfunction

" inoremap <silent><expr> <c-@> coc#refresh()
" nmap <silent> [g <Plug>(coc-diagnostic-prev)
" nmap <silent> ]g <Plug>(coc-diagnostic-next)
" nmap <silent> gd <Plug>(coc-definition)
" nmap <silent> gy <Plug>(coc-type-definition)
" nmap <silent> gi <Plug>(coc-implementation)
" nmap <silent> gr <Plug>(coc-references)
" nmap <leader>rn <Plug>(coc-rename)

" " Use K to show documentation in preview window
" nnoremap <silent> <leader>k :call ShowDocumentation()<CR>

" function! ShowDocumentation()
"   if CocAction('hasProvider', 'hover')
"     call CocActionAsync('doHover')
"   else
"     call feedkeys('K', 'in')
"   endif
" endfunction

" xmap <leader>f  <Plug>(coc-format-selected)
" nmap <leader>f  <Plug>(coc-format-selected)
" command! -nargs=0 Format :call CocActionAsync('format')
" command! -nargs=? Fold :call     CocAction('fold', <f-args>)
" command! -nargs=0 OR   :call     CocActionAsync('runCommand', 'editor.action.organizeImport')
" set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}

